### PR TITLE
Fix for issue #275

### LINKED ISSUE #275: /files API endpoint shall not allow to request paths that do not match ngs.data.root.path
At the moment, it is possible to call `/files` endpoint with a `?path=` parameter which points to a random location within a host machine.
This shall be fixed to deny all requests to a `/files` endpoint which:
* Do not fall into `ngs.data.root.path` parameter location
* Fail all requests if `ngs.data.root.path` is not set or is set to `/` FS root
* Fail all requests if `file.browsing.allowed` is not set or is set to false

### PR DESCRIPTION
**Pull request by SilinPavel**
# Description

This PR resolves #275 issue.

### CODE REVIEW

File: server/catgenome/src/main/java/com/epam/catgenome/security/acl/GrantPermissionManager.java [hunk 1]
```diff
@@ -249,8 +249,10 @@ private void validateParameters(AclClass aclClass, Long entityId, String userNam
             Assert.notNull(userManager.loadUserByName(userName),
                     MessageHelper.getMessage(MessagesConstants.ERROR_ROLE_OR_USER_NOT_FOUND, userName));
         } else {
-            Assert.isTrue(userManager.findGroups(null).stream().anyMatch(group -> group.equalsIgnoreCase(userName))
-                            || roleManager.loadAllRoles(false).stream().anyMatch(r -> r.getName().equalsIgnoreCase(userName)),
+            Assert.isTrue(userManager.findGroups(null).stream()
```
Comment (SilinPavel) [inline server/catgenome/src/main/java/com/epam/catgenome/security/acl/GrantPermissionManager.java:252]: This changes are only cosmetic, just to get rid of checkstyle warnings

File: server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java [hunk 2]
```diff
@@ -1915,17 +1915,19 @@ public void deleteFeatureFileDirectory(FeatureFile featureFile) throws IOExcepti
      * @throws IOException
      */
     public List<AbstractFsItem> loadDirectoryContents(String path) throws IOException {
-        if (!filesBrowsingAllowed) {
+
+        if(!StringUtils.isEmpty(path) && !path.startsWith(ngsDataRootPath)) {
```
Comment (mzueva) [inline server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java]: Is `ngsDataRootPath` always terminated by path separator (`/`)? 
If not, then the following case will allow access:
```
ngsDataRootPath = '/data/storage'
path = '/data/storagesecret'
```

**Review by mzueva — CHANGES_REQUESTED** [review]

File: server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java (hunk 2 above)
Comment (SilinPavel) [reply server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java]: @mzueva that is right. 
Fixed.
Now we check it with startsWith method from Path class, that will perform checking as paths, not just strings.

**Review by mzueva — APPROVED** [review]
